Hotfix/1.1.2
Knox-AAU/DatabaseLayer_DocumentDataAPI pull request #56
Opened 2022-11-15 15:08 UTC by damniko

Husk at den skal merges gennem git flow!

2022-11-16 10:01 UTC, mirakst requested changes
Vi skal lige huske at fjerne det midlertidige table igen! Ellers fantastisk 😄

2022-11-16 10:01 UTC, mirakst commented on DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgWordRelevanceRepository.cs
> +
```suggestion
drop table temp_idf_values;
    ";
```

2022-11-16 14:21 UTC, Sarmisuper approved these changes

2022-11-16 14:21 UTC, Sarmisuper requested changes
Fix linter or else

2022-11-16 16:24 UTC, damniko commented on DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgWordRelevanceRepository.cs
> +
Den findes kun i det ene kald til `con.ExecuteAsync()`, så det skulle ikke være nødvendigt

2022-11-16 18:43 UTC, damniko commented
Opdatering - der var lidt af en kædereaktion:
- Faldt over linjen: `return searchResponses.OrderByDescending(s => s.Relevance).ThenBy(s => s.DocumentModel.Id);` i `NpgSearchRepository.cs`. Har fjernet `.ThenBy` delen da det ikke tilføjer noget værdi til søgeresultaterne (man er vel ligeglad med hvilket dokument der kommer først når der er to med nøjagtig samme relevans), og det er træls at lave en potentielt dyr sortering uden nogen reel effekt
- Efter ovenstående fandt jeg ud af at nogle tests fejlede fordi TF-IDF ikke er udregnet i `populate_tables.sql`, så det script er nu opdateret med de nye værdier
- Som følge af ovenstående fejlede endnu flere tests, som jeg måtte rette til.

Derfor er der så mange ændrede filer.

2022-11-17 08:51 UTC, Sarmisuper approved these changes, later dismissed
![image](https://user-images.githubusercontent.com/72615675/202400255-01e77522-01ef-4844-acd2-49079ba2c633.png)
LGTM

2022-11-17 09:10 UTC, mirakst submitted a review, later dismissed

2022-11-17 09:14 UTC, mirakst approved these changes

2022-11-17 09:14 UTC, Sarmisuper approved these changes

2022-11-17 09:15 UTC, merged